$ANSIBLE_VAULT;1.1;AES256
63623438316430363664666665303332366363353932613332633630323232646431333961303732
3632303665613531653966336363666437383333323336300a653864303337393663373531656661
38313562646639333337623662323233633861636366393764366264383263633566323135313734
3336356261386664360a323030633265626463383266623762343636373665343963316561333937
63333131393735383666616266653333386230636665663463646366393134326362643336643930
62666662363763666365326338663035623437366362386632643430303430663334343766666336
61666137313364343434333535633665383033636239613432643631373830346266303138613066
65656530363039383539363663303265363239396639626538373065323062323032396135313865
31396335666531623734613664613366633930393437653333653131653365313666643135643761
61356533633264323633653332333135353338633635323561386435323830643432386435623564
37316130353133306533323639343462316164643334613034313936306337306634646638653930
36663431376665656232313161616236616661653135363565336566623433343862656666346638
33303830626661643937306335303536313334623537383336616561373663376339613736646435
63666566353066323461353339633165303237363333353565393039633532313661323066303533
65333961353533343136303935393335383336363136633961376434333339626639363835636263
62333936343337363639373639326630616462623363323461666435336337363437346530653161
35336132303562353631323233633039366335313036626663656531613432646630303363633132
64346239653336386135383630393230303135643366376665666164386136636361353963326233
65613432313964666633383061393131366432313763653062333536303766316564343938353962
66383534623566386461643765373634376537363465666433663365623439616333623435376631
3535
