---
- name: Build glances
  include_role:
    name: nix_build
  vars:
    nix_build_attr: nixpkgs#glances
    nix_build_out: /opt/glances

- name: Create s6 service
  include_role:
    name: s6_service
  vars:
    s6_service_name: glances
    s6_service_command: "exec /opt/glances/bin/glances -w"
    s6_service_create_user: false

