---
- name: Build glances
  command: /nix/var/nix/profiles/default/bin/nix build nixpkgs#glances -o /opt/glances
  args:
    creates: /opt/glances

- name: Configure log service
  include_role:
    name: s6-log
  vars:
    s6_log_service_name: glances

- name: Install s6 run script
  template:
    src: run.j2
    dest: /etc/services.d/glances/run
    mode: "0755"

