---
- name: Build glances
  command: /nix/var/nix/profiles/default/bin/nix build nixpkgs#glances -o /opt/glances
  args:
    creates: /opt/glances

- name: Create s6 service
  include_role:
    name: s6_service
  vars:
    s6_service_name: glances
    s6_service_command: "exec /opt/glances/bin/glances -w"
    s6_service_create_user: false

