tunnel: {{ cloudflared_tunnel }}
credentials-file: /etc/cloudflared/{{ cloudflared_tunnel }}.json

ingress:
{% for subdomain in cloudflared_subdomains %}
  - hostname: {{ subdomain }}.{{ cloudflared_domain }}
    service: http://localhost:{{ caddy_http_port }}
{% endfor %}
  - service: http_status:404
